name: Alias Tag Version

on: [repository_dispatch]

jobs:
  alias:

    runs-on: ubuntu-latest

    # only run if the event action is alias tag version
    if: github.event.action == 'alias-tag-version'

    steps:
      - run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker pull paroxity/pmmp:${{ github.event.client_payload.existing }} && docker pull paroxity/pmmp-phpstan:${{ github.event.client_payload.existing }}
          docker tag paroxity/pmmp:${{ github.event.client_payload.existing }} paroxity/pmmp:${{ github.event.client_payload.tag }}
          docker tag paroxity/pmmp-phpstan:${{ github.event.client_payload.existing }} paroxity/pmmp-phpstan:${{ github.event.client_payload.tag }}
          docker push paroxity/pmmp:${{ github.event.client_payload.tag }} && docker push paroxity/pmmp-phpstan:${{ github.event.client_payload.tag }}
