name: Build & Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The target pmmp tag to build an image for."
        required: true
      target_ref:
        description: "The target branch to run workflow for."
        default: "master"
        required: false
      pull:
        description: "Should we pull existing images before the build to speed up the build?"
        default: "false"
        required: false

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Inputs
        run: |
          echo "tag: ${{ github.event.inputs.tag }}"
          echo "target_ref: ${{ github.event.inputs.target_ref }}"
          echo "pull: ${{ github.event.inputs.pull }}"
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
        with:
          # allow targeting a build against any branch
          ref: ${{ github.event.inputs.target_ref }}
      - name: Build & Publish
        uses: ./.github/actions/build-publish
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag: ${{ github.event.inputs.tag }}
          pull: ${{ github.event.inputs.pull }}
