name: Build & Publish

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The target pmmp tag to build an image for."
        required: true
      target_ref:
        description: "The target branch to run workflow for."
        default: "master"
        required: false
      pull:
        description: "Should we pull existing images before the build to speed up the build?"
        default: "true"
        required: false

jobs:
  build:

    runs-on: ubuntu-latest

    # only run if the event action is build & publish
    if: github.event.action == 'build-publish'

    steps:
    - uses: actions/checkout@v2
      with:
        # allow targeting a build against any branch
        ref: ${{ github.event.inputs.target_ref }}
    - uses: ./.github/actions/build-publish
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag: ${{ github.event.inputs.tag }}
        pull: ${{ github.event.inputs.pull }}
